name: Use API Key

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Use Secret API Key
      run: echo "Using secret API Key ${{ secrets.API_KEY }}"
      env: 
        API_KEY: ${{ secrets.API_KEY }}
